// The 10 deep-sea retrieval quests. Each giver waits in the town (or on the
// jetty); each item lies in the sea, guarded by its own Nasty Fish species with
// a secret (but consistent) elemental weakness.
// giverPos: on the new streets/market square. face: [x,z] they look toward
// (default: the market square). look: their appearance (see makeVillager).
export const QUESTS = [
  {
    id: 'anchor', giver: 'Captain Finn', short: 'the Captain', emoji: '⚓',
    item: 'Sunken Anchor', spot: [-20, -70], weakness: 'earth', fishColor: 0x8a3324,
    giverPos: [64, -6], face: [45, 0], npcColor: 0x2b5a8c, shop: null,
    look: { skin: 0xd9a066, hair: 'short', hairColor: 0xdddddd, beard: true, beardColor: 0xf5f5f5,
      top: 0x1f3a5f, bottom: 0x2b2b33, hat: 'captain' },
    line: 'Ahoy, little mer! A storm stole my anchor and my boat drifts free! Fetch my ⚓ Sunken Anchor from the deep and 100 🐚 are yours!',
    thanks: 'My boat is safe again! You are a true friend of the sea. Here — 100 shell coins!',
    reward: { coins: 100 },
  },
  {
    id: 'seaglass', giver: 'Lumi the Lamp-maker', short: 'Lumi', emoji: '🏮',
    item: 'Luminescent Sea-Glass', spot: [-95, -40], weakness: 'wind', fishColor: 0x1f4e79,
    giverPos: [100, 6], face: [100, 0], npcColor: 0xc9a227, shop: null,
    look: { skin: 0xf5d7a8, hair: 'bun', hairColor: 0x1b1b1b, dress: 0xd9a03f, apron: 0x3a4048 },
    line: 'The village streets are so dark at night… Bring me 🏮 Luminescent Sea-Glass and I will craft night-lights for everyone! 100 🐚 reward!',
    thanks: 'It glows like a captured star! The streets will shine tonight. 100 shell coins, with thanks!',
    reward: { coins: 100 },
  },
  {
    id: 'crown', giver: 'Coco', short: 'Coco', emoji: '👑', shop: 'Accessories',
    item: 'Royal Coral Crown', spot: [60, -75], weakness: 'water', fishColor: 0x6a3fa0,
    giverPos: [162.7, -4.8], npcColor: 0xb05a9a,
    look: { skin: 0x5d3a1a, hair: 'afro', hairColor: 0x2a1a12, dress: 0xff6fb5, earrings: true },
    line: 'Darling! Legend tells of a 👑 Royal Coral Crown lost in the deep. Bring it to my shop and I will polish it up FOR YOU to wear!',
    thanks: 'Simply STUNNING on you, darling! The crown is yours — find it in your mirror (Character Creator)! 👑',
    reward: { unlock: 'crown' },
  },
  {
    id: 'ring', giver: 'Poor Pip', short: 'Pip', emoji: '💍',
    item: 'Lost Wedding Ring', spot: [28, 22], weakness: 'fire', fishColor: 0xc76a8a,
    giverPos: [46, 1], jetty: true, face: [34, 0], npcColor: 0x777788,
    look: { skin: 0xfbe0c4, hair: 'short', hairColor: 0xb35a2d, top: 0x8a8a92, bottom: 0x5a4632, sad: true },
    line: '*sniff* I dropped my 💍 wedding ring off the pier while fishing… My heart is broken! Please, can you find it? I saved 100 🐚 for whoever helps.',
    thanks: 'MY RING! Oh happy day! My wife will be over the moon. Take every coin — 100 🐚!',
    reward: { coins: 100 },
  },
  {
    id: 'seaweed', giver: 'Stitch', short: 'Stitch', emoji: '🌈', shop: 'Clothes',
    item: 'Prismatic Seaweed', spot: [-60, 70], weakness: 'fire', fishColor: 0x2e8b57,
    giverPos: [137.3, 4.8], npcColor: 0x4fc08d,
    look: { skin: 0xeec39a, hair: 'ponytail', hairColor: 0x4fc08d, top: 0x2ea6a0, bottom: 0x333344,
      hat: 'beret', hatColor: 0x9b59b6, sash: 0xffd23f },
    line: 'I dream of a dye that shimmers with every colour! Fetch 🌈 Prismatic Seaweed and I will brew a magic dye that makes YOUR scales rainbow!',
    thanks: 'The dye works! Your scales can now shimmer with every colour of the rainbow — look in the Character Creator! 🌈',
    reward: { unlock: 'rainbow' },
  },
  {
    id: 'recipe', giver: 'Barnaby the Baker', short: 'Barnaby', emoji: '📜', shop: 'Food',
    item: 'Ancient Bottle Recipe', spot: [10, -85], weakness: 'water', fishColor: 0xb8860b,
    giverPos: [162.7, 4.8], npcColor: 0xd2691e,
    look: { skin: 0xf3c9a5, hair: 'short', hairColor: 0x8a5a33, stout: true,
      top: 0x8a5a33, bottom: 0x4a3a2a, hat: 'baker', apron: 0xfff7e0 },
    line: 'My great-great-grandmother\'s secret cake recipe was lost at sea in a corked bottle! Find the 📜 Ancient Bottle Recipe and I\'ll bake you a feast!',
    thanks: 'THE LOST RECIPE! Tonight we feast! Eat up — your strength is fully restored, plus 50 🐚 for the road!',
    reward: { coins: 50, feast: true },
  },
  {
    id: 'cushion', giver: 'Plush', short: 'Plush', emoji: '⭐', shop: 'Furniture',
    item: 'Starfish Cushion', spot: [-40, -45], weakness: 'wind', fishColor: 0xe07020,
    giverPos: [145.4, -12.9], npcColor: 0xe0725c,
    look: { skin: 0x8d5524, hair: 'afro', hairColor: 0x1e1e1e, top: 0xe0725c, bottom: 0xfff1d6, hat: 'flower' },
    line: 'Every living room needs a giant plush starfish! Bring me the ⭐ Starfish Cushion and I\'ll share my secret stash of building pearls!',
    thanks: 'Ooooh it\'s so SQUISHY! As promised: 8 shiny building pearls from my private stash! 🫧',
    reward: { pearls: 8 },
  },
  {
    id: 'sponge', giver: 'Cobbler Kelp', short: 'Kelp', emoji: '🧽', shop: 'Shoes',
    item: 'Deep-Sea Sponge', spot: [40, 90], weakness: 'earth', fishColor: 0xdddd55,
    giverPos: [137.3, -4.8], npcColor: 0x8a5a33,
    look: { skin: 0xb97a50, hair: 'bald', beard: true, beardColor: 0x9a9a9a,
      top: 0x556b2f, bottom: 0x3a2a1a, apron: 0x6b4226 },
    line: 'With a 🧽 Deep-Sea Sponge I can craft the comfiest, springiest insoles in the world! Bring one and the first pair is yours!',
    thanks: 'Slip these on! Sponge insoles — you\'ll run faster than anyone on the island! 👟💨',
    reward: { unlock: 'sponge' },
  },
  {
    id: 'nautilus', giver: 'Melody', short: 'Melody', emoji: '🐚',
    item: 'Rainbow Nautilus Shell', spot: [-70, 58], weakness: 'wind', fishColor: 0x20b2aa,
    giverPos: [158, 20], face: [150, 0], npcColor: 0x9370db,
    look: { skin: 0xf3c9a5, hair: 'long', hairColor: 0x9b7fd4, dress: 0x8e6fc0, earrings: true },
    line: 'They say a 🐚 Rainbow Nautilus Shell plays music when you hold it to your ear… I am so lonely without a song. Find it and 100 🐚 are yours.',
    thanks: '*holds it to her ear* …it\'s beautiful. Music at last! Thank you, friend. 100 shell coins!',
    reward: { coins: 100 },
  },
  {
    id: 'trident', giver: 'Elder Maris', short: 'the Elder', emoji: '🔱',
    item: 'The Golden Trident', spot: [-150, 0], weakness: 'fire', fishColor: 0x1a1a2a,
    giverPos: [154, -40], face: [150, 0], npcColor: 0xeeeeee, needsDone: 3,
    look: { skin: 0x5d3a1a, hair: 'long', hairColor: 0xf5f5f5, beard: true, beardColor: 0xf5f5f5,
      dress: 0xf5f0e6, staff: true },
    line: 'Young one… beyond the waterfall lies 🔱 The Golden Trident, guarded by the fiercest fish in all the sea. Return it to the village and 500 🐚 shall be yours. Be brave.',
    thanks: 'The Golden Trident returns at last! The village will never forget you, hero. FIVE HUNDRED shell coins!',
    lockedLine: 'You are not ready, young one. Help three villagers first, then we shall speak of the Trident.',
    reward: { coins: 500 },
  },
];
